### ISSUE TITLE
Missing island

### ISSUE THREAD

**Issue by tarantonio** [orts/server#100]
The link to missing island otbm:
http://www.mediafire.com/download/2y24xycaefjmy02/MISSINGISLANDOTRS.zip

![missingisland](https://cloud.githubusercontent.com/assets/7066891/6898952/8c0ba9f4-d6fd-11e4-9254-44f43e087ed2.png)

**Comment by ninjalulz** [comment]
Thanks!

**Comment by TheSumm** [comment]
Calcanea*
