### ISSUE TITLE
Working on Monster (PICTURES)

### ISSUE THREAD

**Issue by TechrlzGit** [orts/server#110]
http://i.imgur.com/gIi5MmZ.png

Coming Soon..

**Comment by EPuncker** [comment]
great, but put them on their proper folder separated by  please :+1: 

like this: http://tibia.wikia.com/wiki/Monsters#Amphibians

**Comment by TechrlzGit** [comment]
Yes, I am separating this way to see what is missing.

**Comment by Schiffers** [comment]
any news?

**Comment by HyphenMaster** [comment]
Exactly, any news ? :)
