### ISSUE TITLE
Nostalgia Island

### ISSUE THREAD

**Issue by tarantonio** [orts/server#111]
Hi, I managed to find recorded casts for Nostalgia Island
https://www.tibiacast.com/recordings?sort=date&cutoff=all&search=nostalgia+island&world=all&min-level=1&max-level=

Anyone with maptracker working can add it to map.

**Comment by EPuncker** [comment]
we can't add it since sprites were removed from client

**Comment by tarantonio** [comment]
You can at least map zone, without museum.

**Comment by WibbenZ** [comment]
If the spirits were removed we can't add it.
But @EPuncker are you 100% on that? Seems like abit of a waste to add something for one update, when they might use it again at another anniversary. But its cipsoft so who knows lol :P

**Comment by EPuncker** [comment]
100% sure
9.44: http://i.imgur.com/TNLRa5C.png
9.6: http://i.imgur.com/5RSI8zX.png

**Comment by WibbenZ** [comment]
Well as I said.. its cipsoft lol haha
But it looks like they are still gonna use the spirits? Not sure how they have done it in the paste, but shoulden't they have used those ids for other spirits if not?
