### ISSUE TITLE
Missing Raging tower portal

### ISSUE THREAD

**Issue by rikitrini** [orts/server#120]
Hello guys well i see that script was missing on the ot i tried adding, the own script i got and all works but the zao portal not collapses if anyone can fix and change the functions from 1.0 to 1.1 will be great there are the scripts:
raging.lua: http://pastebin.com/rVGWyVbx
energized.lua: http://pastebin.com/P8w80LdH
yielothax.lua http://pastebin.com/ZMZYJTWp
thanks!

**Comment by xxxlordxx** [comment]
could u add npc from this quest?

**Comment by rikitrini** [comment]
well i haven't any npc my friend xd i just got the monster, and that creaturescripts i posted should work perfect on tfs 1.0 but i need change it to tfs 1.1 xd u may need put it on data/creaturescripts/scripts/ http://pastebin.com/JrfiSm1L  and http://pastebin.com/DQTHebJ8 just add the event on your creaturescripts.xml, and the scripts i posted after just make a folder named raging mage tower and put it here data/creatuescripts/scripts/raging tower and put it here  and it work perfect on tfs 1.0 the problem i got i need someone edit it for me for work on tfs 1.1
