### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by HyphenMaster** [orts/server#124]
When I starting my server I get this errors. For example:

stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/walkback.lua:4: in function <data/movements/scripts/walkback.lua:3>

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/snow.lua:onStepOut
data/lib/050-functions.lua:119: attempt to call method 'isPlayer' (a nil value)
stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/snow.lua:2: in function <data/movements/scripts/snow.lua:1>

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/walkback.lua:onStepIn
data/lib/050-functions.lua:119: attempt to call method 'isPlayer' (a nil value)
stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/walkback.lua:4: in function <data/movements/scripts/walkback.lua:3>

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/snow.lua:onStepOut
data/lib/050-functions.lua:119: attempt to call method 'isPlayer' (a nil value)
stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/snow.lua:2: in function <data/movements/scripts/snow.lua:1>

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/walkback.lua:onStepIn
data/lib/050-functions.lua:119: attempt to call method 'isPlayer' (a nil value)
stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/walkback.lua:4: in function <data/movements/scripts/walkback.lua:3>

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/snow.lua:onStepOut
data/lib/050-functions.lua:119: attempt to call method 'isPlayer' (a nil value)
stack traceback:
        [C]: in function 'isPlayer'
        data/lib/050-functions.lua:119: in function 'getPlayer'
        data/movements/scripts/snow.lua:2: in function <data/movements/scripts/snow.lua:1>

**Comment by mimusassasin** [comment]
here the same =(
