### ISSUE TITLE
Bigfoot's Burden Questlog

### ISSUE THREAD

**Issue by rikitrini** [orts/server#125]
Hello guys  i was wondering if someone can make and  upload to the repository the bigfoot's questlog , because i cant find it on any site >.< thanks in advance

**Comment by rikitrini** [comment]
@ninjalulz can i know why my posts was closed? if there's no any questlog updated ?

**Comment by rikitrini** [comment]
@ninjalulz ninja reopen this post -.- i m needing this questlog and im asking for help to ppl lomg

**Comment by ninjalulz** [comment]
I closed this issue because I'm already aware of the issues with this quest, and missing quest log is hardly the biggest issue with the quest.

[This](https://github.com/ninjalulz/FORGOTTENSERVER-ORTS/pull/1498) might help you though.

**Comment by rikitrini** [comment]
@ninjalulz okey! thanks for all ninja

**Comment by rikitrini** [comment]
@ninjalulz one question! it helped me so much b ut for any news where i can check? if someone update more the questlog ect..?
