### ISSUE TITLE
Bigfoot's Burden Rank's Problem

### ISSUE THREAD

**Issue by rikitrini** [orts/server#126]
Hello guys, well im not sure if there is any issue about that because i checked but nothing so i post it , because i checked after i make bigfoot's burden acces and the 2 first tasks of commander stone, i can't make the next quests after i get 30 reputation rank I so i think the problem its the character don't get the next rank/archievement so can't continue the tasks, if someone can help with that! @ninjalulz if there is any issue about it ninja please let me know the exactly post!thanks in advance

**Comment by rikitrini** [comment]
Close it the problem was im rlly stupid xD

**Comment by EPuncker** [comment]
you can close this yourself by clicking close here \/
