### ISSUE TITLE
Training offline

### ISSUE THREAD

**Issue by gianzinho18** [orts/server#127]
Training offline not working 100% only the player up the shield skill and not magic level or other (axe,sword,club).

**Comment by gianzinho18** [comment]
20:24 During your absence you trained for 19 minutes.
20:24 You advanced to shielding level 20.
20:24 Your Shielding skill changed from level 10 (with 0.00% progress towards level 11) to level 20 (with 61.91% progress towards level 21)

**Comment by EPuncker** [comment]
that was a problem with tfs itself, not related to this datapack and has been fixed already
