### ISSUE TITLE
Donkey Mount !!!

### ISSUE THREAD

**Issue by TeFoOBr** [orts/server#138]
the Witch transform mount Donkey, not work ... ty

**Comment by ninjalulz** [comment]
Please elaborate. Taming a donkey works properly for me.

**Comment by Schiffers** [comment]
I'm thinking that using one "if get outfit"... (i don't remeber the function, but...), in the witch will resolve the problem, if the outfit is the donkey return true and try catch the mount, if not, return false

**Comment by TeFoOBr** [comment]
The "monster npc witch transform (incredibly old witch)", transform all time in Skunk, dog, ... never in Donkey... 3 hour looking and no transform....

**Comment by ninjalulz** [comment]
I tested yesterday, and it transformed a few times within a minute or so.

**Comment by tago360** [comment]
I have the same problem.  Tried fixing but does not load donkey at all!
