### ISSUE TITLE
Another Error in potions.lua (addItem function)

### ISSUE THREAD

**Issue by kushovu** [orts/server#148]
Hi!
 i got this error when i try to use a potion from the ground

![sin titulo16](https://cloud.githubusercontent.com/assets/11846161/7131477/73f7f270-e245-11e4-9a76-3f52a355c8f6.jpg)

Also i've seen that is there another issue report of something like this and i went to the updated file and replace the changed lines
https://github.com/orts/server/issues/74

However the error was not the same so i didn't got a solution of this
Any idea?

**Comment by ninjalulz** [comment]
I can't reproduce this.

**Comment by kushovu** [comment]
so i'm the only one getitng this error?
