### ISSUE TITLE
how to change that on ots?

### ISSUE THREAD

**Issue by pitis91** [orts/server#166]
New characters now start with 55 Mana Points instead of just 5.

**Comment by ninjalulz** [comment]
You can use this query to add additional 50 mana to your players.
```SQL
UPDATE `players` SET `mana` = `mana` + 50, `manamax` = `manamax` + 50;
```

**Comment by pitis91** [comment]
yep but I'm speaking about when a player is now created how it starts? with 5mp or 55?

**Comment by ninjalulz** [comment]
It depends on your AAC configuration.

**Comment by pitis91** [comment]
I'm using Znote Acc
