### ISSUE TITLE
Missing depots in Guild Halls

### ISSUE THREAD

**Issue by pitis91** [orts/server#167]
**Ab'Dendriel**
- [ ] Ab'Dendriel Clanhall
- [x] Shadow Towers
- [ ] The Hideout

**Carlin**
- [ ] Carlin Clanhall
- [ ] House of Recreation
- [ ] Northport Clanhall
- [ ] Seawatch
- [ ] Senja Clanhall
- [ ] Suntower

**Darashia**
- [ ] Darashia, Eastern Guildhall

**Edron**
- [ ] Sky Lane, Guild 2
- [ ] Stonehome Clanhall

**Kazordoon**
- [x] Granite Guildhall
- [ ] Hill Hideout
- [ ] Marble Guildhall
- [ ] Outlaw Castle
- [ ] Riverspring
- [ ] Wolftower

**Liberty Bay**
- [ ] Ivy Cottage
- [x] Mountain Hideout
- [x] The Shelter

**Svargrond**
- [ ] Crystal Glance

**Thais**
- [ ] Bloodhall
- [ ] Dark Mansion
- [ ] Greenshore Clanhall
- [ ] Guildhall of the Red Rose
- [ ] Halls of the Adventurers
- [ ] Snake Tower
- [ ] Southern Thais Guildhall
- [ ] Spiritkeep
- [ ] Thais Clanhall

**Comment by pitis91** [comment]
https://mega.co.nz/#!hAESFLZJ!wtYYwfDNHkTYZccHpZBlu8a-orMuWfxhdoshljVM0bI

**Comment by pitis91** [comment]
I've Stoped my Map job till it will be added or not that I've already done, and I will work for my own maybe on map because I got feelings to be useless here.

**Comment by ninjalulz** [comment]
Your contribution is much appreciated, and it will be added in the next following days. I have other things to prioritize at the moment.

**Comment by pitis91** [comment]
ah thanks I will keep working when it's done =P
