### ISSUE TITLE
Problem Map!

### ISSUE THREAD

**Issue by TeFoOBr** [orts/server#181]
Look the imagem thx.
![2015-04-29 21_59_45-server youtibia](https://cloud.githubusercontent.com/assets/10349474/7404564/326b15a8-eebb-11e4-9c02-ba4705cca183.png)

**Comment by ninjalulz** [comment]
Should be fixed in https://github.com/orts/world/commit/85f64cbb067edf24eec889ee7ec123f9ea13bb22
