### ISSUE TITLE
wrong lava id 

### ISSUE THREAD

**Issue by korykora** [orts/server#183]
Position: 33116, 32795, 14
in ancient tombs quest 
![lava](https://cloud.githubusercontent.com/assets/7412995/7444780/1a633e14-f194-11e4-8fde-6b0743ff1cb5.png)

**Comment by pitis91** [comment]
Can you explain a mil more why is wrong or why to get the other side without that way?

**Comment by WibbenZ** [comment]
He is saying it is the wrong sprite = otb bug.
Was the same with the br otb file :p

**Comment by korykora** [comment]
It should look like it the rest of the lava, but it should be possible to stand on the squares.

**Comment by ninjalulz** [comment]
@WibbenZ This is not an otb bug, CipSoft tends to ditch older item ids, and create new ones.

I'll push a fix later today.
