### ISSUE TITLE
urgent bug ???

### ISSUE THREAD

**Issue by TeFoOBr** [orts/server#184]
using a pot down the pot does not add the empty flask, ie, infinite pot
Error in exe (obs: tfs update latest version)

![usechao](https://cloud.githubusercontent.com/assets/10349474/7445625/9d7a1d48-f191-11e4-9663-fe5c9efc8266.png)

One item down
![2015-05-03 12_42_31-tibia - adm](https://cloud.githubusercontent.com/assets/10349474/7445641/f9def7ca-f191-11e4-8cc5-0126a73b641e.png)

Look
![2015-05-03 12_42_50-tibia - adm](https://cloud.githubusercontent.com/assets/10349474/7445642/fefe378e-f191-11e4-9c02-e943a61865d0.png)

**Comment by TeFoOBr** [comment]
I resolved the bug temporary ... comentary de code !

--	if topParent.isItem and (not topParent:isItem() or topParent.itemid ~= 460) then
--		if item:getParent():addItem(potion.emptyId, 1) or topParent:addItem(potion.emptyId, 1) then
--			item:remove(1)
--			return true
--		end
--	end

and remove 
 level = 50}, -- emptyId = 7634

**Comment by gugahoa** [comment]
Just change the second if to:
local parent = item:getParent()
if not parent:isTile() and (parent:addItem(potion.emptyId, 1) or topParent:addItem(potion.emptyId, 1)) then

**Comment by ninjalulz** [comment]
Is this still an issue?

**Comment by pitis91** [comment]
lol if you drop a potion on the floor and later try to drink it from floor never gets empty....
