### ISSUE TITLE
lua script error when god tries look on normal player

### ISSUE THREAD

**Issue by Dzentelmen** [orts/server#195]
Like title says, when you try look on player you didnt get message like "You see..." there is just error in console. But when you are playing as a normal character - not a god then everything works fine.

Error from console:

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onLook
data/lib/050-functions.lua:164: attempt to index global 'bit' (a nil value)
stack traceback:
        [C]: ?
        data/lib/050-functions.lua:164: in function 'convertIpToString'
        data/events/scripts/player.lua:66: in function <data/events/scripts/play
er.lua:8>

**Comment by WibbenZ** [comment]
Is your server and datapack up to date?
No issues here, just checked the code and everything seems fine.

The reason you only have this issue on a god is because that description is only sent out if the player's group has access.

**Comment by TheSumm** [comment]
Not related to this datapack, check your compilation.
