### ISSUE TITLE
[Question] Diapason - NPC Edala

### ISSUE THREAD

**Issue by luanlucian93** [orts/server#204]
• I was looking at the code, and not understand why is added time 24hrs in the script lyre ..

- server/data/actions/scripts/other/music.lua:
player:setStorageValue(Storage.Diapason.LyreTimer, os.time() + 86400)

- server/data/npc/scripts/Edala.lua:
player:setStorageValue(Storage.Diapason.EdalaTimer, os.time() + 86400)

**Comment by ninjalulz** [comment]
If something is incorrect, feel free to submit a pull request.

**Comment by WibbenZ** [comment]
Check wikia, it has to do with the mount.

**Comment by luanlucian93** [comment]
I've never done this process in the global tibia, however from what I understand the wiki, you play the lyre and talk to the NPC. After 24hrs, the process repeats for 7 days. In the script of this lyre adding os.time + 24hrs in storage if the LyreProcess is less than 7, but after speaking with the NPC hi Edala is added again (os.time + 24hrs), however the verification of npc is storage LyreTimer < os.time, is that correct?

sorry my english

**Comment by WibbenZ** [comment]
You are supposed to play it to her 7 times and wait 24h between each playing.
And I just checked the script and there should not be any problems.
