### ISSUE TITLE
Bugged Yasir GlobalEvent

### ISSUE THREAD

**Issue by pitis91** [orts/server#207]
missing iterateArea
to functions libs

**Comment by ninjalulz** [comment]
Nope, the [function](https://github.com/orts/server/blob/master/data/lib/miscellaneous/050-functions.lua#L64-72) is there.

**Comment by pitis91** [comment]
http://i.imgur.com/ghmFC5y.png

**Comment by WibbenZ** [comment]
Just remove that code, dalkon fixed it so it has no use.
