### ISSUE TITLE
Player frozen in certain position

### ISSUE THREAD

**Issue by kosicki123** [orts/server#223]
I was testing the server for the first time today and I've noticed a few problems using the gamemaster.

1- When you teleport to some towns with /town <number>, it crashes the client.
2- When walking in certain places like Port Hope closer to the temple, make the client frozen, you can just logout, nothing else. When you login again, this error is thrown in the server window (hope it helps):
[Error - mysql_real_query] Query: INSERT INTO `players_online` VALUES (2)
Message: Duplicate entry '2' for key 'PRIMARY'
The error is probably jumping the logout action and not removing the user online from database. But why?

Sorry if this is only my problem. Here's what I've done to reproduce:
1- I'm using Mac OS X Yosemite.
2- I have follow the tutorial to compile.
3- I'm running the client on Windows.
4- There's no possibility of low memory or low resources on my hardware. Both my computers are high-end.
5- I've downloaded latest source from forgotten server and latest source from here too, both server and map.

Thanks!

**Comment by ninjalulz** [comment]
It's working properly for me on Windows. What does the error report tell you?

**Comment by kosicki123** [comment]
The message of duplicate entry is the only message I've got.
I'm going to try it on windows, thanks!
