### ISSUE TITLE
wierd monster behavior - walk path

### ISSUE THREAD

**Issue by MVJohnsen** [orts/server#234]
There is something wrong with how creatures move in this server.
I have added a youtube video to kind of show what im talking about, because its hard to explain.

- Creatures uses alot of time to "figure" out where you are it seems, they will turn almost like you turn ur character CTRL -> Arrow keys direction at the time and then use 2 seconds to start walking again.
Issue does get worse the faster you are and the more you change directions. It dosent feel like real tibia to me. I play as a paladin IRL aswell..

Here is the youtube link -> https://www.youtube.com/watch?v=gWUYA6_trMg

PS - I have seen creature lag caused by computer spec limitations, this is not it.
        My computer is a six core i7 with 32gb of ram.

**Comment by ninjalulz** [comment]
Not related to this datapack.
