### ISSUE TITLE
[ERROR] Attempt to call method 'isItem' (a nil value)

### ISSUE THREAD

**Issue by luanlucian93** [orts/server#235]
Lua Script Error: [Action Interface] 
data/actions/scripts/other/destroy.lua:onUse
data/actions/lib/actions.lua:89: attempt to call method 'isItem' (a nil value)
stack traceback:
	[C]: in function 'isItem'
	data/actions/lib/actions.lua:89: in function <data/actions/lib/actions.lua:88>
	(...tail calls...)

**Comment by ninjalulz** [comment]
How do you reproduce this?

**Comment by luanlucian93** [comment]
this report on my server, 100 + players, do not know how to reproduce it

**Comment by ninjalulz** [comment]
You're probably missing the Creature method isItem.

https://github.com/orts/server/blob/master/data/lib/core/creature.lua#L38-40
