### ISSUE TITLE
[ENCHANTING] - Gives to much mlvl.

### ISSUE THREAD

**Issue by MVJohnsen** [orts/server#255]
By enchanting rubies etc, you can get magic level 180 in a day on this server.
Does anyone know where to fix this?

**Comment by ninjalulz** [comment]
Simply remove the magic skill multiplier from enchanting.lua.

**Comment by MVJohnsen** [comment]
Could you please give me an example? 
I cant seem to find a multiplier in the lua. 

Are you talking about this one?

player:addMana(-mana)
player:addSoul(-soul)
item:transform(enchantedGems[targetId])
player:addManaSpent(mana * configManager.getNumber(configKeys.RATE_MAGIC))
player:getPosition():sendMagicEffect(CONST_ME_HOLYDAMAGE)
return true
end

**Comment by joseluis2g** [comment]
player:addManaSpent(mana * configManager.getNumber(configKeys.RATE_MAGIC)) to player:addManaSpent(mana)

**Comment by MVJohnsen** [comment]
Thank you :)
