### ISSUE TITLE
Oramond House Doors

### ISSUE THREAD

**Issue by kanohn** [orts/server#260]
In map editor have a door in oramond with a item ID (22826):
http://s29.postimg.org/acomh1b7b/house1.png

In-game the ID changes to 22819 automatically:
http://s9.postimg.org/rfbl9frfz/house2.png

Im using the same items.otb in Datapack and RME, the items.otb are official. The oramond map i get from Orts.

I testes and saw that if i put the door id 22826 without a house tile, its appear 100%, but why in house dont works?

Please help!

**Comment by gantit** [comment]
You need use Oficial [OTMB](https://github.com/orts/server/blob/master/data/items/items.otb) to solved.

**Comment by Stoudemire** [comment]
same problem
