### ISSUE TITLE
Shaman outfits quest 

### ISSUE THREAD

**Issue by Stoudemire** [orts/server#274]
NPC Hairycles not give shaman outfit

**Comment by ninjalulz** [comment]
He does, you have to say either outfit or shamanic once you have completed the quest.

**Comment by Stoudemire** [comment]
yes, but when any player complete and tell to him about outfit or shamanic powers the NPC says 	"You are shaman and doctor. Me proud of you", and not give the shaman outfit

**Comment by Stoudemire** [comment]
https://gyazo.com/f7fcf91502fb2bf6184936457384e707
