### ISSUE TITLE
Unknown floorChange error

### ISSUE THREAD

**Issue by Strutzz** [orts/server#285]
Anyone know what this error is?

```
[Warning - Items::parseItemNode] Unknown floorChange: eastex
[Warning - Items::parseItemNode] Unknown floorChange: southex
```

**Comment by Tarliton** [comment]
it was removed
https://github.com/otland/forgottenserver/commit/70590833b25f6b6a137c5e45ce29b254edddadf8

**Comment by WibbenZ** [comment]
@TheSumm This can be closed, already fixed.
