### ISSUE TITLE
[to-do] Update monsters looktype

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#57]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Saturday Feb 14, 2015 at 03:01 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/1593_

----

We need to update monsters looktype and corpses IDs (mostly minotaurs) as soon as tfs is updated

PS: opened this issue just to not forget it

edit: and add new corpses to obsidian knife

**Comment by WibbenZ** [comment]
We also have to update the npcs to give a shopping bag insted of a backpack when they buy using the "with backpack" function.
(http://tibia.wikia.com/wiki/Shopping_Bag)[Source]
