### ISSUE TITLE
player.lua 

### ISSUE THREAD

**Issue by Stoudemire** [orts/server#66]
![f7fb2fb98b9f8d8e95c7f5bd57008b5b](https://cloud.githubusercontent.com/assets/6404685/6445709/423bbd8c-c0dc-11e4-98a6-1503ded206b2.png)

**Comment by TheSumm** [comment]
Not related to the datapack.
Your engine is not compiled correctly.

**Comment by Stoudemire** [comment]
how i can compile correctly?
