### ISSUE TITLE
about potions

### ISSUE THREAD

**Issue by Schiffers** [orts/server#68]
hi folks, I'm thinking, when you use potions with this scripts, they remove the potion used, and add a new item in your backpack, but, in the tibia global they don't remove the potion, just transform in a empty the potion, with this the potion not go to your first backpack, he stay in your place ... so,
if rewrite the script potions, in the end, just transforming the potion in a empty potion, i don't know how to do this, so I ask for you guys .. 

sorry for my bad english

**Comment by Chuitox** [comment]
In theory this is exactly the same thing as TFS does. A potion and and empty flask have different IDs.

If by using a potion in TFS you don't get the same results as in the official Tibia servers then you should report it to TFS

**Comment by vinioliveirasilva** [comment]
may need only substitute the functions remove and add  for the function transform

```
item:transform(itemId[, count/subType = 1])
```

i will teste tomorrow.

**Comment by ninjalulz** [comment]
Should be fixed in c33a274.

**Comment by Schiffers** [comment]
thanks for answer, and resolve :)
