### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by TeFoOBr** [orts/server#69]
because all these changes, at the end the code was changed to perform the same function?
and another that the code is around dirtier, heavier for a reading?

**Comment by EPuncker** [comment]
![wat8](https://cloud.githubusercontent.com/assets/4684880/6498632/07a328ac-c2cd-11e4-9bc7-f4743754639b.jpg)

**Comment by TeFoOBr** [comment]
???
and that you do not understand, why development should a confused for you...
you not had good practices in development ...
do it to 7 years ... so trained in analysis and software development
I will not even discuss with you

**Comment by vinioliveirasilva** [comment]
I think he is not confused about the development, but because of your English. Yes, the codes were changed to do the same thing, however differently, optimized, ensuring greater stability of the server. The codes may seem difficult, but with a little help from MetaTable function list, you'll be fine.

**Comment by TheSumm** [comment]
No idea what the question is, if you want an answer try having someone who speaks better English translate it for you.

**Comment by TeFoOBr** [comment]
sorry i'm br KKK.... more Vini ty ;)

Yes, the codes were changed to do the same thing, however differently, optimized, ensuring greater stability of the server. << 

I'm not confused, my English and confused

just wanted to know why so much change, I understand the codes, I do so formed to reading it.

ty .

**Comment by TeFoOBr** [comment]
another question, there is an online server this server posted here?
