### ISSUE TITLE
Error in potions.lua (addItem)

### ISSUE THREAD

**Issue by Popzi** [orts/server#74]
Hey!

Just noticed when the script calls item:getParent():addItem(potion.emptyId, 1)
It attempts to index a nil value. Was changed recently from player:addItem

	Lua Script Error: [Action Interface]
	data/actions/scripts/other/potions.lua:onUse
	data/actions/scripts/other/potions.lua:74: attempt to call method 'addItem' (a nil value)
	stack traceback:
	 [C]: in function 'addItem'
	 data/actions/scripts/other/potions.lua:74: in function <data/actions/scripts/other/potions.lua:35>
	
	Lua Script Error: [Action Interface]
	data/actions/scripts/other/potions.lua:onUse
	data/actions/scripts/other/potions.lua:74: attempt to call method 'addItem' (a nil value)
	stack traceback:
	 [C]: in function 'addItem'
	 data/actions/scripts/other/potions.lua:74: in function <data/actions/scripts/other/potions.lua:35>

Sincerely

**Comment by TheSumm** [comment]
How would I reproduce it?

**Comment by Popzi** [comment]
I actually have no idea when it happened, I went on to push the latest commit and while in screen I noticed this error. I tried to reproduce but have been unsuccessful doing it myself, I tried health potions in first container then health potions in a second bag inside first container but no success there either. I'll try every type of potion available to reproduce.

**Comment by Popzi** [comment]
Ok, found how you can reproduce it.

Place for instance 100 health potions on the ground, then browse field and use the health potions on you. The error occurs after you drink a health potion and then drinks another. It will not place any empty flask on top of your ground potions. Same behaviour as I got while testing, see my last post and Edit2. But here it throws the error as in the first post.

The Browse Field makes it buggy, as I assume this is server sided and you can not place items inside the "Browse Field" container. (like if you put a bag on the ground and drink from it, it will add a empty flask in the bag). So this might be related to forgottenserver aswell.

**Comment by TheSumm** [comment]
Check if everything works with https://github.com/orts/server/commit/b2503acaa2cac0608b2fa0e4e23de621d4b594af

**Comment by vinioliveirasilva** [comment]
Fixed to me with https://github.com/orts/server/commit/b2503acaa2cac0608b2fa0e4e23de621d4b594af

**Comment by Popzi** [comment]
Yes, can confirm it's working for me with b2503acaa2cac0608b2fa0e4e23de621d4b594af

Thanks @TheSumm :bowtie:
