### ISSUE TITLE
not is a issue, but I need help !!

### ISSUE THREAD

**Issue by Schiffers** [orts/server#80]
Well guys, I have one script of melting horn ... to use in the frozen ursagrodon, with rand and storage ... but he isn't work properly and I don't know why
if someone help I will appreciate :) and we can use in the data pack
here is my code.
*******************************
local function revertIce(position, itemId, transformId)
	local item = Tile(position):getItemById(itemId)
	if item then
		item:transform(transformId)
	end
end
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
local rand = math.random(1, 100)
	if target.itemid == 22726 and player:getStorageValue(22724) < 1 then
		if((rand >= 1) and (rand < 50)) then
			player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'The ice cracked and the frozen creature with it - be more careful next time!')
			item:remove(1)
			target:transform(22729)
			addEvent(revertIce, 40000, toPosition, 22729, 22726)
		elseif((rand >= 50) and (rand < 100)) then
			player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'You managed to melt about half of the ice blook. Quickly now, it\'s ice cold here and the ice block could freeze over again.')
			target:transform(22727)
		end
	end
	if target.itemid == 22727 and player:getStorageValue(22724) < 1 then
		if((rand >= 1) and (rand < 50)) then
			player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'The ice cracked and the frozen creature with it - be more careful next time!')
			item:remove(1)
			target:transform(22729)
			addEvent(revertIce, 40000, toPosition, 22729, 22726)
		elseif((rand >= 50) and (rand < 100)) then
			player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'You managed to melt almost the whole block, only the feet of the creature are still stuck in the ice. Finish the job!')
			target:transform(22728)
		end
	end
	if target.itemid == 22728 and player:getStorageValue(22724) < 1 then
		if((rand >= 1) and (rand < 50)) then
			player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'The ice cracked and the frozen creature with it - be more careful next time!')
			item:remove(1)
			target:transform(22729)
			addEvent(revertIce, 40000, toPosition, 22729, 22726)
		elseif((rand >= 50) and (rand < 100)) then
			item:remove(1)
			target:transform(22729)
			player:addMount(38)
			player:setStorageValue(22722, 1)
			addEvent(revertIce, 40000, toPosition, 22729, 22726)
		return player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'The freed ursagrodon look at you with glowing, obedient eyes.')
		end
	end
	if player:getStorageValue(22724) >= 1 then
		player:sendTextMessage(MESSAGE_EVENT_ADVANCE, 'You already have the obedience of ursagrodon.')
	end
	return true
end
*******************************
thanks

**Comment by ninjalulz** [comment]
[Support](https://otland.net/forums/support.16/)

**Comment by Schiffers** [comment]
i will not post there, so, can you post for me or something like that? 
:)

**Comment by Schiffers** [comment]
I fix ;)
