### ISSUE TITLE
Warzone rewards right

### ISSUE THREAD

**Issue by EPuncker** [orts/server#81]
Seems like we miss the proper behavior for rewards as well, on real tibia only those who did at least 1 of damage to the respective boss can open the reward chest

**Comment by ninjalulz** [comment]
We already have the proper behavior for reward chests. Only players who are within the damage map will have their storage value changed.

[WarzoneKill.lua#L18-27](https://github.com/orts/server/blob/master/data/creaturescripts/scripts/quests/bigfoot%20burden/WarzoneKill.lua#L18-27)
