### ISSUE TITLE
Loyalty points

### ISSUE THREAD

**Issue by EPuncker** [orts/server#82]
It is something that real tibia have and seems kinda nice to have both here and default tfs, what do you guys think?

**Comment by Schiffers** [comment]
I think that is a nice idea, but how treat this ? how the players will gain loyalty points ? for what they will be used, if will show in an ACC, need do some things

**Comment by WibbenZ** [comment]
http://www.tibia.com/news/?subtopic=newsarchive&id=3067
Could be cool I guess, but would probbly be better fixing bugs right now insted of adding new things.

**Comment by xxxlordxx** [comment]
JESTWEEM
