### ISSUE TITLE
no really a bug BUT...

### ISSUE THREAD

**Issue by Schiffers** [orts/server#83]
well, in warzones, when you do for the first time...
and open one chest
the player receive a msg only of achievement exemple:

13:43 Congratulations! You earned the achievement "Death from Below".

and not the msg like that
"You have found 2 major crystalline tokens, 1 prismatic ring, 1 mucus plug, 10 violet crystal shards and 5 crystal coins.

**Comment by ninjalulz** [comment]
It's not supposed to be any reward message (used TibiaCast recordings as reference).

**Comment by Schiffers** [comment]
AFF BRO, I play the shit tibia global, my char is level 200, I make warzone for 6 months all day, and you say this? ...
man, when you use the chest , the first msg is about the cap, "please make sure that you have.............."
and when use the second time you get the items and have a msg "You have found 2 major crystalline tokens..............."...
go search

**Comment by ninjalulz** [comment]
I have searched, and none of the videos I have watched contain any reward message for those chests.

**Comment by Schiffers** [comment]
seems my mistake, sorry
but I'm right about this: independent of your cap and container the msg "please make sure that you have.............." will appear when you use for the first time after kill boss, and the second use you will gain the reward items
