### ISSUE TITLE
Extra experience with stamina

### ISSUE THREAD

**Issue by Vichoko** [orts/server#93]
The stamina bonus should be 50% bonus exp. But its giving 120% bonus exp.

For example, an orc gives 25 Experience Points. Using the default configuration it is giving 55 experience, and it should give 37 exp. That's an 120% bonus exp vs 50% bonus exp.

Anyone knows how to fix this?

**Comment by ninjalulz** [comment]
The happy hour bonus applies 50 percent extra experience already (25 * 1.5 = 37). You're probably using TFS 1.0 with the onGainExperience changes that are meant for TFS 1.1.
