### ISSUE TITLE
doors cant close

### ISSUE THREAD

**Issue by Stoudemire** [orts/server#95]
![bug](https://cloud.githubusercontent.com/assets/6404685/6886042/ce88705a-d5fe-11e4-8f29-0029e9b37f65.png)

**Comment by Popzi** [comment]
The lua was updated with the 10.76,
https://github.com/otland/forgottenserver/commit/4da1360db922fd8d7adce06300c266741e4fadfc
& fixed bugs from that:
https://github.com/otland/forgottenserver/commit/52546a96f70cbabd4fefaba8301557cc743725db
https://github.com/otland/forgottenserver/commit/8d4745e6fcd3caf69cc5c941869fe5c2b27c903f
I'm on a pad so I can't make a pull for theese changes im afraid :/

**Comment by ninjalulz** [comment]
You need to use LuaJIT DLL's.
