### ISSUE TITLE
Open and Close Answer Issue

### ISSUE THREAD

**Issue by pitis91** [orts/server#98]
Can someone give me maptracker compiled from tibia 10.76?
I just now tracked sight of surrender mountain full and I need map tracker to convert into a map.

https://github.com/jo3bingham/sharpmaptracker

but i can't compile it
there's all maptracker released(compilled). now just till 10.75 but works fine to me on 10.76
https://github.com/jo3bingham/sharpmaptracker/releases

**Comment by Schiffers** [comment]
you convert your tracked to map ?

**Comment by pitis91** [comment]
yep uploaded on next issue

**Comment by Schiffers** [comment]
ya, thanks, I'll update my map :3
thanks thanks

**Comment by pitis91** [comment]
np all that I can help I always try to help =D

**Comment by Schiffers** [comment]
yes. very nice, bro .. and the part near of surrenders, >/\ 
that are missing in the map of datapack, you can try track too ? XD

**Comment by pitis91** [comment]
yep I know what spot but I can't run fast with my ek without get trapped there :(

**Comment by Schiffers** [comment]
I'm sorry, I lost my character hehe'
because the authenticator...
anyway, gogo with ED, calls one for fun, and track this XD
