### ISSUE TITLE
Sight of Surrender Valley Map

### ISSUE THREAD

**Issue by pitis91** [orts/server#99]
I've Tracked that little missing Roshamuul Spot:
http://www.mediafire.com/download/9ugfps7uw32yn13/Sight+of+Surrender+Valley.rar

**Comment by Schiffers** [comment]
bro, you can track the "lion's rock"... :3 easy, I've tracked but I lost the map :(

**Comment by pitis91** [comment]
lion's rock is tracked...

**Comment by Schiffers** [comment]
where?

**Comment by ninjalulz** [comment]
Thanks!

**Comment by Schiffers** [comment]
thanks
